#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=16gb,walltime=00:30:00
#PBS -N app-compute-dice-parcellations
#PBS -V

if [ ! -f ./parc_stats/parc-stats/parcellation.csv ]; then
  time singularity exec -e docker://brainlife/dipy:1.4.1 python3 ./compute_dice_parcellations.py
fi

if [ ! -f ./parc_stats/parc-stats/parcellation.csv ]; then
  echo "something went wrong"
  exit 1
else
  echo "complete"
  exit 0
fi
